import numpy as np
import scipy as sp
from lisatools.utils.constants import PC_SI, YRSID_SI
from bbhx.waveformbuild import BBHWaveformFD


DAY_SI = 24*3600
TOBS = YRSID_SI
dt = 5.
N = int(TOBS / dt)
TOBS = N * dt
freqs = np.fft.rfftfreq(N,dt)
freqs[0] = freqs[1] # have to do this as freqs[0] = 0 causes issues with the waveform generator

FIXED_PARAMETERS = {
    "m1": 1e5,
    "m2": 2e5,
    "chi1z": 0.1,
    "chi2z": 0.7,
    "dist": 2 * 1e9 * PC_SI,
    "phi_ref": 1.0,
    "f_ref": 0.0,
    "t_ref": TOBS - 5*DAY_SI # chose to have the merger at 5 days before the end of the observation time
}

MODES = [(2,2), (2,1), (3,3), (3,2), (4,4), (4,3)]

wave_gen = BBHWaveformFD(amp_phase_kwargs=dict(run_phenomd=False))

NPERSEG = int(60*60*24/dt)  # 1 day segments
NOVERLAP = NPERSEG//2  # 12 hour overlap


def waveform_generator_frequency_domain(
        parameters: np.ndarray
    ):
    
    wave_freq_domain = wave_gen(
        m1=FIXED_PARAMETERS["m1"],
        m2=FIXED_PARAMETERS["m2"],
        chi1z=FIXED_PARAMETERS["chi1z"],
        chi2z=FIXED_PARAMETERS["chi2z"],
        distance=FIXED_PARAMETERS["dist"],
        phi_ref=FIXED_PARAMETERS["phi_ref"],
        f_ref=FIXED_PARAMETERS["f_ref"],
        inc=parameters[0],
        lam=parameters[1],
        beta=parameters[2],
        psi=parameters[3],
        t_ref=FIXED_PARAMETERS["t_ref"],
        freqs=freqs,
        modes=MODES,
        direct=False,   # If direct = True, the waveform is generated directly in the frequency domain. If direct = False, the waveform is generated by interpolating <length> number of frequencies
        length=1024,    # Commonly used value = 1024 for speed
        squeeze=True,   # Idk what this does
        compress=True,  # If direct = False, it is ignored entirely and the modes are always summed. If direct = True, and compress = True (default), the modes are summed.
        fill=True,      # Default is False. If true, the combine argument can be used
        combine=True    # Combines all waveforms into an overlapping waveform. Usually, for one waveform, the shape is [1,3,<length of frequncies>], but if combine is True, the shape is [3,<length of frequencies>]
        )

    return wave_freq_domain

def waveform_generator_time_domain(
        wave_freq_domain
    ):
    wave_time_domain = sp.fft.irfft(wave_freq_domain, axis=-1)
    return wave_time_domain


def stft_transform(
        wave_time_domain,
        dt=dt,
        nperseg=NPERSEG,  # 1 day segments
        noverlap=NOVERLAP  # 12 hour overlap
    ):
    f_stft, t_stft, zxx = sp.signal.stft(
        wave_time_domain,
        fs=1/dt,
        nperseg=nperseg,
        noverlap=noverlap
    )
    return f_stft, t_stft, zxx


def compute_maximas(
        zxx
    ):
    max_zxx = np.max(np.abs(zxx), axis=0)
    return max_zxx